site_name: Things I Learned
site_description: A personal knowledge base documenting my journey as a software engineer.
site_author: Amrit Upreti
site_url: https://amritupreti.github.io/docs/

nav:
  - Welcome: index.md
  - Go: 
    - Basics: 'go/intro.md'
  - DSA:
    - Patterns: 'DSA/patterns.md'
  - HAProxy: 'haproxy/haproxy.md'
  - MongoDB:
    - Replication: 'mongo/replication.md'
    - Sharding: 'mongo/sharding.md'
  - Vim: 'vim/vim.md'

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/amritupreti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amritupreti/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2025 <a href="https://github.com/amritupreti"  target="_blank" rel="noopener">Amrit Upreti</a>
